# Generated by Django 2.0.6 on 2018-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsNotification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='level',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='unit',
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
