# Generated by Django 2.0.6 on 2018-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsNotification', '0002_auto_20180609_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.IntegerField(default=0, verbose_name='Block'),
        ),
    ]
