# Generated by Django 2.0.6 on 2018-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsNotification', '0003_auto_20180609_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address'},
        ),
    ]
