# Generated by Django 2.0.6 on 2018-06-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsNotification', '0004_auto_20180609_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
    ]
